docker stop family_budget_develop_seq
docker stop family_budget_develop_api
docker stop family_budget_develop_mysql

docker rm family_budget_develop_seq
docker rm family_budget_develop_api
docker rm family_budget_develop_mysql