// <auto-generated />
using System;
using Dal.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230707164814_AddedSomeTrainComponentRelations")]
    partial class AddedSomeTrainComponentRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.TrainComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CanAssignQuantity")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("TrainComponents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanAssignQuantity = false,
                            Name = "Engine",
                            Number = "ENG123"
                        },
                        new
                        {
                            Id = 2,
                            CanAssignQuantity = false,
                            Name = "Passenger Car",
                            Number = "PAS456"
                        },
                        new
                        {
                            Id = 3,
                            CanAssignQuantity = false,
                            Name = "Freight Car",
                            Number = "FRT789"
                        },
                        new
                        {
                            Id = 4,
                            CanAssignQuantity = true,
                            Name = "Wheel",
                            Number = "WHL101"
                        },
                        new
                        {
                            Id = 5,
                            CanAssignQuantity = true,
                            Name = "Seat",
                            Number = "STS234"
                        },
                        new
                        {
                            Id = 6,
                            CanAssignQuantity = true,
                            Name = "Window",
                            Number = "WIN567"
                        },
                        new
                        {
                            Id = 7,
                            CanAssignQuantity = true,
                            Name = "Door",
                            Number = "DR123"
                        },
                        new
                        {
                            Id = 8,
                            CanAssignQuantity = true,
                            Name = "Control Panel",
                            Number = "CTL987"
                        },
                        new
                        {
                            Id = 9,
                            CanAssignQuantity = true,
                            Name = "Light",
                            Number = "LGT456"
                        },
                        new
                        {
                            Id = 10,
                            CanAssignQuantity = true,
                            Name = "Brake",
                            Number = "BRK789"
                        },
                        new
                        {
                            Id = 11,
                            CanAssignQuantity = true,
                            Name = "Bolt",
                            Number = "BLT321"
                        },
                        new
                        {
                            Id = 12,
                            CanAssignQuantity = true,
                            Name = "Nut",
                            Number = "NUT654"
                        },
                        new
                        {
                            Id = 13,
                            CanAssignQuantity = false,
                            Name = "Engine Hood",
                            Number = "EH789"
                        },
                        new
                        {
                            Id = 14,
                            CanAssignQuantity = false,
                            Name = "Axle",
                            Number = "AX456"
                        },
                        new
                        {
                            Id = 15,
                            CanAssignQuantity = false,
                            Name = "Piston",
                            Number = "PST789"
                        },
                        new
                        {
                            Id = 16,
                            CanAssignQuantity = true,
                            Name = "Handrail",
                            Number = "HND234"
                        },
                        new
                        {
                            Id = 17,
                            CanAssignQuantity = true,
                            Name = "Step",
                            Number = "STP567"
                        },
                        new
                        {
                            Id = 18,
                            CanAssignQuantity = false,
                            Name = "Roof",
                            Number = "RF123"
                        },
                        new
                        {
                            Id = 19,
                            CanAssignQuantity = false,
                            Name = "Air Conditioner",
                            Number = "AC789"
                        },
                        new
                        {
                            Id = 20,
                            CanAssignQuantity = false,
                            Name = "Flooring",
                            Number = "FLR456"
                        },
                        new
                        {
                            Id = 21,
                            CanAssignQuantity = true,
                            Name = "Mirror",
                            Number = "MRR789"
                        },
                        new
                        {
                            Id = 22,
                            CanAssignQuantity = false,
                            Name = "Horn",
                            Number = "HRN321"
                        },
                        new
                        {
                            Id = 23,
                            CanAssignQuantity = false,
                            Name = "Coupler",
                            Number = "CPL654"
                        },
                        new
                        {
                            Id = 24,
                            CanAssignQuantity = true,
                            Name = "Hinge",
                            Number = "HNG987"
                        },
                        new
                        {
                            Id = 25,
                            CanAssignQuantity = true,
                            Name = "Ladder",
                            Number = "LDR456"
                        },
                        new
                        {
                            Id = 26,
                            CanAssignQuantity = false,
                            Name = "Paint",
                            Number = "PNT789"
                        },
                        new
                        {
                            Id = 27,
                            CanAssignQuantity = true,
                            Name = "Decal",
                            Number = "DCL321"
                        },
                        new
                        {
                            Id = 28,
                            CanAssignQuantity = true,
                            Name = "Gauge",
                            Number = "GGS654"
                        },
                        new
                        {
                            Id = 29,
                            CanAssignQuantity = false,
                            Name = "Battery",
                            Number = "BTR987"
                        },
                        new
                        {
                            Id = 30,
                            CanAssignQuantity = false,
                            Name = "Radiator",
                            Number = "RDR456"
                        });
                });

            modelBuilder.Entity("Domain.TrainComponentContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TrainComponentContexts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Main"
                        });
                });

            modelBuilder.Entity("Domain.TrainComponentRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ContextId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TrainComponentId")
                        .HasColumnType("int");

                    b.Property<int?>("TrainComponentParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id", "TrainComponentId", "TrainComponentParentId")
                        .IsUnique();

                    b.ToTable("TrainComponentRelations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContextId = 1,
                            TrainComponentId = 2
                        },
                        new
                        {
                            Id = 2,
                            ContextId = 1,
                            Quantity = 4,
                            TrainComponentId = 4,
                            TrainComponentParentId = 1
                        },
                        new
                        {
                            Id = 3,
                            ContextId = 1,
                            Quantity = 4,
                            TrainComponentId = 7,
                            TrainComponentParentId = 1
                        },
                        new
                        {
                            Id = 4,
                            ContextId = 1,
                            Quantity = 1,
                            TrainComponentId = 8,
                            TrainComponentParentId = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
